### ISSUE TITLE
blog on daily routines of sw-engineer

### ISSUE THREAD

**Issue by oleksmarkh** [oleksmarkh/oleksmarkh.github.io#5]
# activities
- micro-planning
- pair-programming
- coding
- testing
- suggestions, discussions, flames etc.
- feature flow and personal impact/attitude
- meetings
- sport and other physical activities
- random chats
# principles
- openness
- ability to comprehend complex cases
- ways to integrate (applicable to both sw and people) 
- transparency and traceability (planning, notifications, log, search)
- maintainability (being concise, modular)
- terminology: patterns, definitions
- tools (unix way + orchestration)
- stateless mind :)
- vision
- two-way feedback, review (with analysis)
- mentoring, growing up the environment around
- reflection (bugs are good!)
- "breaking things" vs. "why to touch it if it (somehow) works"
- visuals
- communities and involvement (both local and open)
# tools
- chats
- trackers
- storages
- editors (prominent features)
- subscriptions (business and public)
- flows and conventions
- lists (of lists): backlog, pen+paper etc.
- schedulers, notificators, calendars
- terminal (and tmux)
- hotkeys
# conditions
- air, oxygen
- water
- noise
- desc
  *equipment/hardware
- meeting rooms
- communication channels
# examples
- justifying deps migration/rotation https://github.com/obviel/obviel/issues/8

draw some sort of diagram to glue it all together, lol

**Comment by markhovskiy** [comment]
give some scoped examples, use metaphors: vehicle, body, Pferdegespann :)

**Comment by markhovskiy** [comment]
http://www.slideshare.net/zazworka/identifying-and-managing-technical-debt

**Comment by markhovskiy** [comment]
think about how to advertise:
* who to ask for a review
* make sure that channels are healthy
* prepare all public profiles
* where (twitter, fb, dou?) and when (week day, time) to share
* book some time to address feedback

**Comment by markhovskiy** [comment]
post another one, about this one (what's learned, what's next)

**Comment by YevKov** [comment]
Please update channels list: add hackernews/reddit (I'm not sure how easy it is to publish on hackernews. Better to check before actual publication).

**Comment by YevKov** [comment]
By my personal feeling, quite a big part of time (especially when challenging change request is coming) we spend on procrastination instead of identifying and handling it (how to find when it starts happening? how to avoid? define sub-tasks / continuous integration of big change / to identify dark parts of big task and fight against).

It's not related to anything mentioned above, so I think it's good to keep it in mind on final review of post.
